name: 'terraform-summary'
description: 'Generate a summary of Terraform plan on your PR'
author: 'OneZero Company'

inputs:
  github-token:
    description: 'The GitHub token'
    required: true
    default: ${{ github.token }}
  folders:
    description: 'The folders to run terraform plan on'
    required: true

outputs:
  summary:
    description: 'The summary of Terraform plan'

runs:
  using: node20
  main: dist/index.js
