name: 'terraform-summary'
description: 'Generate a summary of Terraform plan on your PR'
author: 'OneZero Company'

inputs:
  github-token:
    description: 'The GitHub token'
    required: true
    default: ${{ github.token }}
  folder:
    description: 'The folders to run terraform plan on'
    required: true
  title:
    description: 'The title of the summary'
    default: 'Terraform Plan'
  id:
    description: 'ID of the summary'
    default: 'terraform-plan'

outputs:
  markdown:
    description: 'The markdown content of the summary'
  json:
    description: 'The json content of the summary'
  has_changes:
    description: 'Whether the plan has changes'

runs:
  using: node20
  main: dist/index.js
